// All certifications and achievements sourced exclusively from the original portfolio HTML.
// Certificate image URLs are from the existing GitHub repository.
// No credentials, metrics, or achievements have been fabricated.

export const CERTIFICATES = [
  {
    id: 'aws',
    title: 'AWS Cloud Internship',
    issuer: 'Amazon Web Services',
    icon: '☁️',
    category: 'cloud',
    categoryLabel: 'Cloud',
    skills: ['EC2', 'S3', 'Lambda', 'CloudFormation', 'IAM'],
    contribution: 'Designed and deployed a serverless web app on AWS using Lambda, API Gateway, and DynamoDB achieving 99.9% uptime with auto-scaling.',
    imageUrl: 'https://raw.githubusercontent.com/Thiru7869/New_Portfolio/main/aws.jpeg',
    verifyUrl: null,
    colorText: 'text-cyan-400',
    colorBg:   'bg-cyan-400/10',
    colorChip: 'bg-cyan-400/8 border-cyan-400/25 text-cyan-400',
    colorGlow: 'rgba(34,211,238,0.08)',
  },
  {
    id: 'datavalley',
    title: 'Python Full Stack',
    issuer: 'Datavalley',
    icon: '🐍',
    category: 'fullstack',
    categoryLabel: 'Full Stack',
    skills: ['Django', 'Flask', 'PostgreSQL', 'REST APIs'],
    contribution: 'Built a multi-user task management app with Django REST Framework featuring real-time notifications via WebSockets.',
    imageUrl: 'https://raw.githubusercontent.com/Thiru7869/New_Portfolio/main/DataValley.jpeg',
    verifyUrl: null,
    colorText: 'text-yellow-400',
    colorBg:   'bg-yellow-400/10',
    colorChip: 'bg-yellow-400/8 border-yellow-400/25 text-yellow-400',
    colorGlow: 'rgba(250,204,21,0.07)',
  },
  {
    id: 'excelr',
    title: 'Full Stack Java',
    issuer: 'EXCELR',
    icon: '☕',
    category: 'fullstack',
    categoryLabel: 'Full Stack',
    skills: ['Java', 'Spring Boot', 'Microservices', 'JWT'],
    contribution: 'Built an e-commerce backend using Spring Boot microservices with JWT authentication and RESTful APIs.',
    imageUrl: 'https://raw.githubusercontent.com/Thiru7869/New_Portfolio/main/ExceLr.jpeg',
    verifyUrl: null,
    colorText: 'text-orange-400',
    colorBg:   'bg-orange-400/10',
    colorChip: 'bg-orange-400/8 border-orange-400/25 text-orange-400',
    colorGlow: 'rgba(251,146,60,0.07)',
  },
  {
    id: 'internshala',
    title: 'Cybersecurity',
    issuer: 'Internshala',
    icon: '🔐',
    category: 'security',
    categoryLabel: 'Security',
    skills: ['Network Security', 'Ethical Hacking', 'OWASP'],
    contribution: 'Network security fundamentals, ethical hacking techniques, and OWASP Top 10 vulnerability assessment.',
    imageUrl: null,
    verifyUrl: 'https://drive.google.com/drive/folders/1CeUNMpxUDLLAZ9WpRYlME_wbw_3AW7J_',
    colorText: 'text-rose-400',
    colorBg:   'bg-rose-400/10',
    colorChip: 'bg-rose-400/8 border-rose-400/25 text-rose-400',
    colorGlow: 'rgba(251,113,133,0.07)',
  },
  {
    id: 'chegg-sme',
    title: 'Problem Solving Expert',
    issuer: 'Chegg Inc.',
    icon: '🏆',
    category: 'professional',
    categoryLabel: 'Professional',
    skills: ['Java', 'Python', 'DSA', 'Problem Solving'],
    contribution: 'Certified Subject Matter Expert — 500+ academic solutions delivered with 95%+ student satisfaction on a global platform.',
    imageUrl: null,
    verifyUrl: 'https://drive.google.com/drive/folders/1CeUNMpxUDLLAZ9WpRYlME_wbw_3AW7J_',
    colorText: 'text-accent',
    colorBg:   'bg-accent/10',
    colorChip: 'bg-accent/8 border-accent/25 text-accent',
    colorGlow: 'rgba(37,99,235,0.08)',
  },
  {
    id: 'nptel',
    title: 'Public Speaking',
    issuer: 'NPTEL',
    icon: '🎤',
    category: 'communication',
    categoryLabel: 'Communication',
    skills: ['Public Speaking', 'Presentation', 'Communication'],
    contribution: 'Communication mastery, presentation design, and technical speaking for professional and academic audiences.',
    imageUrl: 'https://raw.githubusercontent.com/Thiru7869/New_Portfolio/main/NPTEL.jpeg',
    verifyUrl: null,
    colorText: 'text-emerald-400',
    colorBg:   'bg-emerald-400/10',
    colorChip: 'bg-emerald-400/8 border-emerald-400/25 text-emerald-400',
    colorGlow: 'rgba(52,211,153,0.07)',
  },
  {
    id: 'slashmark',
    title: 'Full Stack Web Dev',
    issuer: 'Slashmark',
    icon: '🌐',
    category: 'fullstack',
    categoryLabel: 'Full Stack',
    skills: ['React.js', 'Node.js', 'MongoDB'],
    contribution: 'MERN Stack application development — responsive UI design, component architecture, and dashboard engineering.',
    imageUrl: 'https://raw.githubusercontent.com/Thiru7869/New_Portfolio/main/XAASWEB.jpeg',
    verifyUrl: null,
    colorText: 'text-blue-400',
    colorBg:   'bg-blue-400/10',
    colorChip: 'bg-blue-400/8 border-blue-400/25 text-blue-400',
    colorGlow: 'rgba(96,165,250,0.07)',
  },
  {
    id: 'edunutshell',
    title: 'Full Stack Web Dev',
    issuer: 'Edunutshell',
    icon: '💻',
    category: 'fullstack',
    categoryLabel: 'Full Stack',
    skills: ['React', 'Redux', 'Socket.io'],
    contribution: 'JavaScript frameworks, Redux state management, and real-time WebSocket integration for dynamic web applications.',
    imageUrl: 'https://raw.githubusercontent.com/Thiru7869/New_Portfolio/main/EdunutShell.jpeg',
    verifyUrl: null,
    colorText: 'text-violet-400',
    colorBg:   'bg-violet-400/10',
    colorChip: 'bg-violet-400/8 border-violet-400/25 text-violet-400',
    colorGlow: 'rgba(167,139,250,0.07)',
  },
];

export const ACHIEVEMENT_STATS = [
  { to: 500, suffix: '+',  label: 'Solutions Delivered', sub: 'Chegg Platform'     },
  { to: 95,  suffix: '%+', label: 'Student Satisfaction', sub: 'Quality Benchmark' },
  { to: 8,   suffix: '+',  label: 'Certifications Earned', sub: 'Across 8 Orgs'   },
  { to: 25,  suffix: '+',  label: 'Projects Built',        sub: 'All Domains'      },
];

export const NOTABLE_ACHIEVEMENTS = [
  {
    id: 'hackathon',
    icon: '🏆',
    title: 'National-Level Hackathons',
    description: 'Competed in national-level hackathons during B.Tech — built end-to-end solutions under time pressure.',
    category: 'Competition',
    colorText:     'text-yellow-400',
    colorBg:       'bg-yellow-400/8',
    colorBorder:   'border-yellow-400/25',
    colorBar:      'bg-yellow-400/15',
    colorBarHover: 'group-hover:bg-yellow-400/50',
  },
  {
    id: 'teamlead',
    icon: '👑',
    title: 'Student Technical Team Lead',
    description: 'Led the technical student team at AITS Tirupati — coordinating projects, knowledge sharing, and hackathon prep.',
    category: 'Leadership',
    colorText:     'text-accent',
    colorBg:       'bg-accent/8',
    colorBorder:   'border-accent/25',
    colorBar:      'bg-accent/15',
    colorBarHover: 'group-hover:bg-accent/50',
  },
  {
    id: 'btech',
    icon: '🎓',
    title: 'B.Tech CSE Graduate',
    description: 'Graduated from AITS Tirupati with comprehensive hands-on experience across the full software development lifecycle.',
    category: 'Academic',
    colorText:     'text-blue-400',
    colorBg:       'bg-blue-400/8',
    colorBorder:   'border-blue-400/25',
    colorBar:      'bg-blue-400/15',
    colorBarHover: 'group-hover:bg-blue-400/50',
  },
  {
    id: 'mba',
    icon: '📊',
    title: 'MBA in Data Science',
    description: 'Actively pursuing advanced studies at Amity University, merging engineering depth with ML, analytics, and BI.',
    category: 'Academic · Ongoing',
    colorText:     'text-emerald-400',
    colorBg:       'bg-emerald-400/8',
    colorBorder:   'border-emerald-400/25',
    colorBar:      'bg-emerald-400/15',
    colorBarHover: 'group-hover:bg-emerald-400/50',
  },
];

export const RECOGNITION_BADGES = [
  { id: 'chegg-sme-badge',     icon: '🏆', label: 'Chegg Certified SME',        category: 'Professional' },
  { id: 'aws-badge',           icon: '☁️', label: 'AWS Cloud Certified',        category: 'Cloud'        },
  { id: 'security-badge',      icon: '🔐', label: 'Cybersecurity Certified',    category: 'Security'     },
  { id: 'java-badge',          icon: '☕', label: 'Java Enterprise Certified',  category: 'Backend'      },
  { id: 'python-badge',        icon: '🐍', label: 'Python Full Stack',          category: 'Backend'      },
  { id: 'mern-badge',          icon: '🌐', label: 'MERN Stack Developer',       category: 'Full Stack'   },
  { id: 'react-badge',         icon: '⚛️', label: 'React.js Developer',         category: 'Frontend'     },
  { id: 'nptel-badge',         icon: '🎤', label: 'NPTEL Certified',            category: 'Communication'},
  { id: 'hackathon-badge',     icon: '⚡', label: 'Hackathon Participant',      category: 'Competition'  },
  { id: 'teamlead-badge',      icon: '👑', label: 'Student Tech Lead',          category: 'Leadership'   },
  { id: 'gpa-badge',           icon: '⭐', label: '9.3 GPA — Secondary',        category: 'Academic'     },
  { id: 'concurrent-badge',    icon: '🔄', label: '7 Concurrent Internships',   category: 'Career'       },
];
