// All experience data sourced exclusively from the original portfolio HTML.
// No responsibilities, metrics, or achievements have been invented.

export const PROFESSIONAL_ROLE = {
  company: 'Chegg Inc.',
  monogram: 'C',
  role: 'Subject Matter Expert',
  type: 'Remote / Freelance',
  domain: 'EdTech · Computer Science',
  duration: '2022 – Present',
  description:
    'Serving as a Computer Science and Programming expert on Chegg\'s global platform, providing in-depth, step-by-step solutions to complex academic problems. Maintaining 95%+ satisfaction across 500+ solutions.',
  responsibilities: [
    'Deliver step-by-step solutions to complex CS, programming, and mathematical problems',
    'Maintain 95%+ quality benchmark across hundreds of answered questions',
    'Cover 10+ subject areas including DSA, Web Dev, Python, Java, and SQL',
    'Support students through algorithmic thinking and software design principles on a global scale',
  ],
  stats: [
    { to: 500, suffix: '+',  label: 'Solutions Delivered' },
    { to: 95,  suffix: '%+', label: 'Student Satisfaction' },
    { to: 3,   suffix: '+',  label: 'Years Active' },
    { to: 10,  suffix: '+',  label: 'Subject Areas' },
  ],
  tech: ['Java', 'Python', 'JavaScript', 'C++', 'SQL', 'React', 'Node.js', 'Spring Boot', 'Django', 'DSA'],
};

export const INTERNSHIPS = [
  {
    id: 'aws',
    icon: '☁️',
    company: 'Amazon Web Services',
    role: 'AWS Cloud Internship',
    preview: 'Cloud computing, EC2, S3, Lambda, serverless architecture',
    contribution:
      'Designed and deployed a serverless web application on AWS using Lambda, API Gateway, and DynamoDB achieving 99.9% uptime with auto-scaling.',
    tech: ['AWS EC2', 'S3', 'Lambda', 'CloudFormation', 'IAM'],
    colorText: 'text-cyan-400',
    colorBg: 'bg-cyan-400/8',
    colorBorder: 'border-cyan-400/25',
    colorGlow: 'rgba(34,211,238,0.08)',
  },
  {
    id: 'datavalley',
    icon: '🐍',
    company: 'Datavalley',
    role: 'Python Full Stack',
    preview: 'Django, Flask, REST APIs, PostgreSQL backend mastery',
    contribution:
      'Developed a multi-user task management application with Django REST Framework featuring real-time notifications via WebSockets.',
    tech: ['Django', 'Flask', 'PostgreSQL', 'REST APIs'],
    colorText: 'text-yellow-400',
    colorBg: 'bg-yellow-400/8',
    colorBorder: 'border-yellow-400/25',
    colorGlow: 'rgba(250,204,21,0.08)',
  },
  {
    id: 'excelr',
    icon: '☕',
    company: 'EXCELR',
    role: 'Full Stack Java',
    preview: 'Spring Boot, microservices, enterprise Java applications',
    contribution:
      'Built a fully-featured e-commerce backend using Spring Boot microservices with JWT authentication and RESTful APIs.',
    tech: ['Java', 'Spring Boot', 'Microservices', 'JWT'],
    colorText: 'text-orange-400',
    colorBg: 'bg-orange-400/8',
    colorBorder: 'border-orange-400/25',
    colorGlow: 'rgba(251,146,60,0.08)',
  },
  {
    id: 'internshala',
    icon: '🔐',
    company: 'Internshala',
    role: 'Cybersecurity',
    preview: 'Network security, ethical hacking, OWASP assessment',
    contribution: null,
    tech: ['Network Security', 'Ethical Hacking', 'OWASP'],
    colorText: 'text-rose-400',
    colorBg: 'bg-rose-400/8',
    colorBorder: 'border-rose-400/25',
    colorGlow: 'rgba(251,113,133,0.08)',
  },
  {
    id: 'slashmark',
    icon: '🌐',
    company: 'Slashmark',
    role: 'Full Stack Web Dev',
    preview: 'MERN Stack, responsive UI design and dashboards',
    contribution: null,
    tech: ['React.js', 'Node.js', 'MongoDB'],
    colorText: 'text-blue-400',
    colorBg: 'bg-blue-400/8',
    colorBorder: 'border-blue-400/25',
    colorGlow: 'rgba(96,165,250,0.08)',
  },
  {
    id: 'edunutshell',
    icon: '💻',
    company: 'Edunutshell',
    role: 'Full Stack Web Dev',
    preview: 'JavaScript frameworks, Redux, WebSockets',
    contribution: null,
    tech: ['React', 'Redux', 'Socket.io'],
    colorText: 'text-violet-400',
    colorBg: 'bg-violet-400/8',
    colorBorder: 'border-violet-400/25',
    colorGlow: 'rgba(167,139,250,0.08)',
  },
  {
    id: 'nptel',
    icon: '🎤',
    company: 'NPTEL',
    role: 'Public Speaking',
    preview: 'Communication, presentation design & technical speaking',
    contribution: null,
    tech: ['Public Speaking', 'Presentation'],
    colorText: 'text-emerald-400',
    colorBg: 'bg-emerald-400/8',
    colorBorder: 'border-emerald-400/25',
    colorGlow: 'rgba(52,211,153,0.08)',
  },
  {
    id: 'chegg-sme',
    icon: '🏆',
    company: 'Chegg Inc.',
    role: 'Problem Solving Expert',
    preview: 'Certified SME — 500+ solutions, 95%+ student satisfaction',
    contribution: null,
    tech: ['Java', 'Python', 'DSA'],
    colorText: 'text-accent',
    colorBg: 'bg-accent/8',
    colorBorder: 'border-accent/25',
    colorGlow: 'rgba(37,99,235,0.08)',
  },
];

export const RESUME_URL = 'https://drive.google.com/file/d/1tf1CfdDaZpWJ4SvDiEV7sYd1Z4y-eBiY/view';
